### ISSUE TITLE
add k8s namespace and podname to *-deploy.yaml files

### ISSUE THREAD

**Issue by jpetto** [mozmeao/basket-config#16]
```yaml
- name: K8S_NAMESPACE
  valueFrom:
    fieldRef:
      fieldPath: metadata.namespace
- name: K8S_POD_NAME
  valueFrom:
    fieldRef:
      fieldPath: metadata.name
```
